name: abi pipeline

on: push

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello
        run: echo "Hello World"
      - name: Check Java version
        run: java -version

      - name: List files
        run: ls
